export const API_CALL_REQUEST = "API_TRANSACTIONS_REQUEST";
export const API_CALL_SUCCESS = "API_TRANSACTIONS_SUCCESS";
export const API_CALL_FAILURE = "API_TRANSACTIONS_FAILURE";

export const INCREMENT_AMOUNT = "INCREMENT_AMOUNT";
export const DECREMENT_AMOUNT = "DECREMENT_AMOUNT";

export const TRANSACTION_TOGGLE = "TRANSACTION_TOGGLE";
export const MARK_TRANSACTION_AS_PAID = "MARK_TRANSACTION_AS_PAID";

export const UPLOAD_CSV_REQUEST = "UPLOAD_CSV_REQUEST";
export const UPLOAD_CSV_SUCCESS = "UPLOAD_CSV_SUCCESS";
export const UPLOAD_CSV_FAILURE = "UPLOAD_CSV_FAILURE";

// LOGIN
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
