export const API_CALL_REQUEST = "API_TRANSACTIONS_REQUEST";
export const API_CALL_SUCCESS = "API_TRANSACTIONS_SUCCESS";
export const API_CALL_FAILURE = "API_TRANSACTIONS_FAILURE";

export const INCREMENT_AMOUNT = "INCREMENT_AMOUNT";
export const DECREMENT_AMOUNT = "DECREMENT_AMOUNT";
